//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Barometer) DeepCopyInto(out *Barometer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Barometer.
func (in *Barometer) DeepCopy() *Barometer {
	if in == nil {
		return nil
	}
	out := new(Barometer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Barometer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BarometerList) DeepCopyInto(out *BarometerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Barometer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BarometerList.
func (in *BarometerList) DeepCopy() *BarometerList {
	if in == nil {
		return nil
	}
	out := new(BarometerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BarometerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BarometerSpec) DeepCopyInto(out *BarometerSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Threshold != nil {
		in, out := &in.Threshold, &out.Threshold
		*out = new(PSI)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BarometerSpec.
func (in *BarometerSpec) DeepCopy() *BarometerSpec {
	if in == nil {
		return nil
	}
	out := new(BarometerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BarometerStatus) DeepCopyInto(out *BarometerStatus) {
	*out = *in
	if in.Pressure != nil {
		in, out := &in.Pressure, &out.Pressure
		*out = make(map[string]*PSI, len(*in))
		for key, val := range *in {
			var outVal *PSI
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(PSI)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BarometerStatus.
func (in *BarometerStatus) DeepCopy() *BarometerStatus {
	if in == nil {
		return nil
	}
	out := new(BarometerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PSI) DeepCopyInto(out *PSI) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(StallMetrics)
		(*in).DeepCopyInto(*out)
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(StallMetrics)
		(*in).DeepCopyInto(*out)
	}
	if in.IO != nil {
		in, out := &in.IO, &out.IO
		*out = new(StallMetrics)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PSI.
func (in *PSI) DeepCopy() *PSI {
	if in == nil {
		return nil
	}
	out := new(PSI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StallMetric) DeepCopyInto(out *StallMetric) {
	*out = *in
	if in.Avg10 != nil {
		in, out := &in.Avg10, &out.Avg10
		*out = new(int32)
		**out = **in
	}
	if in.Avg60 != nil {
		in, out := &in.Avg60, &out.Avg60
		*out = new(int32)
		**out = **in
	}
	if in.Avg300 != nil {
		in, out := &in.Avg300, &out.Avg300
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StallMetric.
func (in *StallMetric) DeepCopy() *StallMetric {
	if in == nil {
		return nil
	}
	out := new(StallMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StallMetrics) DeepCopyInto(out *StallMetrics) {
	*out = *in
	if in.Some != nil {
		in, out := &in.Some, &out.Some
		*out = new(StallMetric)
		(*in).DeepCopyInto(*out)
	}
	if in.Full != nil {
		in, out := &in.Full, &out.Full
		*out = new(StallMetric)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StallMetrics.
func (in *StallMetrics) DeepCopy() *StallMetrics {
	if in == nil {
		return nil
	}
	out := new(StallMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThresholdSpec) DeepCopyInto(out *ThresholdSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThresholdSpec.
func (in *ThresholdSpec) DeepCopy() *ThresholdSpec {
	if in == nil {
		return nil
	}
	out := new(ThresholdSpec)
	in.DeepCopyInto(out)
	return out
}
