apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: barometer
spec:
  selector:
    matchLabels:
      app: barometer
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: barometer
    spec:
      serviceAccountName: {{ include "barometer.serviceAccountName" . }}
      containers:
      - name: barometer
        image: ko://github.com/ellistarn/barometer/cmd/barometer
        securityContext:
          privileged: true
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /sys/fs/cgroup/kubepods.slice
          name: cgroup
      volumes:
      - hostPath:
          path: /sys/fs/cgroup/kubepods.slice
          # type: ""
        name: cgroup
